Repository pestphp/pest-plugin-browser, pull requests merged in 2025-02, with the labels that each got.

#41 chore: make the tests use the playground instead of laravel.com
  playground/composer.json
  playground/resources/css/app.css
  playground/resources/views/index.blade.php
  playwright.config.js
  tests/Browser/Operations/AssertDontSeeTest.php
  tests/Browser/Operations/AssertSeeTest.php
  tests/Browser/Operations/AssertTitleContainsTest.php
  tests/Browser/Operations/AssertTitleTest.php
  tests/Browser/Operations/AssertUrlIsTest.php
  tests/Browser/Operations/BackAndForwardTest.php
  tests/Browser/Operations/ClickLinkTest.php
  tests/Browser/Operations/RefreshTest.php
  tests/Browser/Operations/ScreenshotTest.php
  tests/Browser/Operations/VisitTest.php
Labels: question

#38 feat : Assert attribute
  README.md
  src/Operations/AssertAttribute.php
  src/PendingTest.php
  tests/Browser/Operations/AssertAttributeTest.php
Labels: awaits documentation

#42 feat: Add `pause` operation to PendingTest
  README.md
  src/Operations/Pause.php
  src/PendingTest.php
  tests/Browser/Operations/PauseTest.php
Labels: awaits documentation

#32 feat: assert query string has
  README.md
  src/Operations/AssertQueryStringHas.php
  src/Operations/AssertQueryStringMissing.php
  src/PendingTest.php
  tests/Browser/Operations/AssertQueryStringHasTest.php
  tests/Browser/Operations/AssertQueryStringMissingTest.php
Labels: awaits documentation

#40 Add assertScript assertion
  README.md
  src/Operations/AssertScript.php
  src/PendingTest.php
  tests/Browser/Operations/AssertScript.php
Labels: awaits documentation

#35 Add assertVisible and assertMissing assertions
  README.md
  src/Operations/AssertMissing.php
  src/Operations/AssertVisible.php
  src/PendingTest.php
  tests/Browser/Operations/AssertMissingTest.php
  tests/Browser/Operations/AssertVisibleTest.php
Labels: awaits documentation

#60 feat : assert attribute doesnt contain
  README.md
  peck.json
  src/Operations/AssertAttributeDoesntContain.php
  src/PendingTest.php
  tests/Browser/Operations/AssertAttributeDoesntContainTest.php
Labels: awaits documentation, awaits changes

#64 feat: Add new assertions for URL paths
  README.md
  src/Operations/AssertPathBeginsWith.php
  src/Operations/AssertPathContains.php
  src/Operations/AssertPathEndsWith.php
  src/Operations/AssertPathIs.php
  src/Operations/AssertPathIsNot.php
  src/PendingTest.php
  tests/Browser/Operations/AssertPathBeginsWith.php
  tests/Browser/Operations/AssertPathContains.php
  tests/Browser/Operations/AssertPathEndsWith.php
  tests/Browser/Operations/AssertPathIs.php
  tests/Browser/Operations/AssertPathIsNot.php
Labels: awaits documentation, awaits changes
